### ISSUE TITLE
Running Import-CrmDataPackage stand alone

### ISSUE THREAD

**Issue by eugenevanstaden** [abvogel/Microsoft.Xrm.DevOps.Data#11]
Hi Andrew,

Can I execute Import-CrmDataPackage command as standalone, ie. something like this:
**$Conn = Get-CrmConnection -Interactive
Import-CrmDataPackage -Conn $Conn -ZipPath "etcetc"**

I'd like to run Import as a seperate step in my release process?

**Comment by dylanberry** [comment]
I'm looking for the same functionality. From what I can see the cmdlet only writes some basic output but doesn't connect to anything.

https://github.com/abvogel/Microsoft.Xrm.DevOps.Data/blob/c863ff4922dc812fffb357c38d90cab229c10c48/Microsoft.Xrm.DevOps.Data.PowerShell/Cmdlets/Import-CrmDataPackage.cs#L50

**Comment by abvogel** [comment]
The Import-CrmDataPackage commands imports a data package from a zip file into a PowerShell object. To import into a CRM environment you could use https://www.powershellgallery.com/packages/Microsoft.Xrm.Tooling.ConfigurationMigration/

**Comment by dylanberry** [comment]
Thanks Andrew, I'm learning my way around the Dynamics world and pointing me in the right direction is truly a big help!

**Comment by abvogel** [comment]
That library I linked to is really difficult to find. It's a shame Microsoft doesn't update their articles to reference it! Glad to help!
