### ISSUE TITLE
skipupdate attribute on entity is dropped when merging data packages

### ISSUE THREAD

**Issue by ScottColson** [abvogel/Microsoft.Xrm.DevOps.Data#13]
Data packages that are imported do not pick up the skipupdate attribute on the entity that the datamigration utility includes in the schema file.

**Comment by abvogel** [comment]
Thanks Scott. Which entity were you trying to import that had the skipupdate attribute?

**Comment by ScottColson** [comment]
The new Data Migration Util sets a skipupdate attribute in the entity element in the data_schema.xml file. If you generate a zipped data package using the utility and then try to merge it with another zipped data package, the skipupdate attribute is dropped. I've got a PR just about ready.
